import { GraphQLResponse } from '../api/apis/metadataApi.js';
import { MetadataResponse } from '../api/apis/vizqlDataServiceApi.js';

interface Field {
  name?: string;
  columnClass?: string;
  logicalTableId?: string | null;
  dataType?: string | null;
  defaultAggregation?: string | null;
  description?: string | null;
  descriptionInherited?: Array<{ attribute: string; value: string | null } | null> | null;
  dataCategory?: string | null;
  role?: string | null;
  defaultFormat?: string | null;
  semanticRole?: string | null;
  aggregation?: string | null;
  aggregationParam?: string | null;
  formula?: string | null;
  isAutoGenerated?: boolean | null;
  hasUserReference?: boolean | null;
  binSize?: number | null;
}

interface Parameter {
  name?: string;
  parameterType?: string;
  dataType?: string | null;
  value?: number | string | boolean | null;
  members?: unknown[];
  min?: number | null;
  max?: number | null;
  step?: number | null;
  minDate?: string | null;
  maxDate?: string | null;
  periodValue?: number | null;
  periodType?: string | null;
}

interface LogicalTableGroup {
  logicalTableId: string | null;
  fields: Field[];
}

export interface FieldsResult {
  datasourceDescription: string;
  fieldGroups: LogicalTableGroup[];
  parameters: Parameter[];
}

export function getGraphqlQuery(datasourceLuid: string): string {
  return `
  query datasourceFieldInfo {
    publishedDatasources(filter: { luid: "${datasourceLuid}" }) {
      name
      description
      owner {
        name
      }
      fields {
        name
        isHidden
        description
        descriptionInherited {
          attribute
          value
        }
        fullyQualifiedName
        __typename
        upstreamTables {
          name
        }
        ... on AnalyticsField {
          __typename
        }
        ... on ColumnField {
          dataCategory
          role
          dataType
          defaultFormat
          semanticRole
          aggregation
          aggregationParam
        }
        ... on CalculatedField {
          dataCategory
          role
          dataType
          defaultFormat
          semanticRole
          aggregation
          aggregationParam
          formula
          isAutoGenerated
          hasUserReference
        }
        ... on BinField {
          dataCategory
          role
          dataType
          formula
          binSize
        }
        ... on GroupField {
          dataCategory
          role
          dataType
          hasOther
        }
        ... on CombinedSetField {
          delimiter
          combinationType
        }
      }
    }
  }`;
}

function normalizeLogicalTableId(logicalTableId?: string | null): string | null {
  if (logicalTableId == undefined) return null;
  const normalized = logicalTableId.trim();
  return normalized.length > 0 ? normalized : null;
}

function groupFieldsByLogicalTableId(fields: Field[]): LogicalTableGroup[] {
  const grouped = new Map<string | null, Field[]>();
  for (const field of fields) {
    const key = field.logicalTableId ?? null;
    const existing = grouped.get(key) ?? [];
    existing.push(field);
    grouped.set(key, existing);
  }
  return [...grouped.entries()].map(([logicalTableId, fields]) => ({ logicalTableId, fields }));
}

function populateFieldWithAdditionalProperties(sourceField: Record<string, unknown>, targetField: Field): void {
  if (sourceField.description) targetField.description = sourceField.description as string;
  if (Array.isArray(sourceField.descriptionInherited) && sourceField.descriptionInherited.length) {
    targetField.descriptionInherited = sourceField.descriptionInherited as Field['descriptionInherited'];
  }
  if (sourceField.dataCategory) targetField.dataCategory = sourceField.dataCategory as string;
  if (sourceField.role) targetField.role = sourceField.role as string;
  if (sourceField.defaultFormat) targetField.defaultFormat = sourceField.defaultFormat as string;
  if (sourceField.formula) {
    targetField.formula = sourceField.formula as string;
    if (sourceField.isAutoGenerated != undefined) targetField.isAutoGenerated = sourceField.isAutoGenerated as boolean;
    if (sourceField.hasUserReference != undefined) targetField.hasUserReference = sourceField.hasUserReference as boolean;
  }
  if (sourceField.binSize != undefined) targetField.binSize = sourceField.binSize as number;
}

export function simplifyReadMetadataResult(readMetadataResult: MetadataResponse): FieldsResult {
  const result: FieldsResult = { datasourceDescription: '', fieldGroups: [], parameters: [] };

  if (!readMetadataResult.data) return result;

  const fields: Field[] = [];
  for (const field of readMetadataResult.data) {
    const toPush: Field = {
      name: field.fieldCaption,
      dataType: field.dataType,
      columnClass: field.columnClass,
      logicalTableId: normalizeLogicalTableId(field.logicalTableId),
    };
    if (field.defaultAggregation) toPush.defaultAggregation = field.defaultAggregation;
    if (field.formula) toPush.formula = field.formula;
    fields.push(toPush);
  }

  // Populate parameters
  const extraData = (readMetadataResult as Record<string, unknown>).extraData as
    | { parameters?: Array<Record<string, unknown>> }
    | undefined;
  if (extraData?.parameters) {
    for (const param of extraData.parameters) {
      const toPush: Parameter = {
        name: param.parameterCaption as string,
        parameterType: param.parameterType as string,
        dataType: param.dataType as string,
        value: param.value as Parameter['value'],
      };
      if (param.parameterType === 'LIST' && param.members) {
        toPush.members = param.members as unknown[];
      } else if (param.parameterType === 'QUANTITATIVE_DATE') {
        toPush.minDate = param.minDate as string | null;
        toPush.maxDate = param.maxDate as string | null;
        toPush.periodValue = param.periodValue as number | null;
        toPush.periodType = param.periodType as string | null;
      } else if (param.parameterType === 'QUANTITATIVE_RANGE') {
        toPush.min = param.min as number | null;
        toPush.max = param.max as number | null;
        toPush.step = param.step as number | null;
      }
      result.parameters.push(toPush);
    }
  }

  result.fieldGroups = groupFieldsByLogicalTableId(fields);
  return result;
}

export function combineFields(
  readMetadataResult: MetadataResponse,
  listFieldsResult: GraphQLResponse,
): FieldsResult {
  const combinedFields: FieldsResult = {
    datasourceDescription: listFieldsResult.data.publishedDatasources[0]?.description ?? '',
    fieldGroups: [],
    parameters: [],
  };
  const fields: Field[] = [];

  if (!readMetadataResult.data) {
    // Fallback to GraphQL results
    const ds = listFieldsResult.data.publishedDatasources[0];
    if (ds?.fields.length) {
      for (const field of ds.fields) {
        const toPush: Field = { name: field.name, logicalTableId: null };
        if (field.dataType) toPush.dataType = field.dataType;
        if (field.aggregation) toPush.defaultAggregation = field.aggregation;
        populateFieldWithAdditionalProperties(field as unknown as Record<string, unknown>, toPush);
        fields.push(toPush);
      }
    }
    combinedFields.fieldGroups = groupFieldsByLogicalTableId(fields);
    return combinedFields;
  }

  // Build fields from VizQL Data Service
  for (const field of readMetadataResult.data) {
    const toPush: Field = {
      name: field.fieldCaption,
      dataType: field.dataType,
      columnClass: field.columnClass,
      logicalTableId: normalizeLogicalTableId(field.logicalTableId),
    };
    if (field.defaultAggregation) toPush.defaultAggregation = field.defaultAggregation;
    if (field.formula) toPush.formula = field.formula;
    fields.push(toPush);
  }

  // Populate parameters
  const extraData = (readMetadataResult as Record<string, unknown>).extraData as
    | { parameters?: Array<Record<string, unknown>> }
    | undefined;
  if (extraData?.parameters) {
    for (const param of extraData.parameters) {
      const toPush: Parameter = {
        name: param.parameterCaption as string,
        parameterType: param.parameterType as string,
        dataType: param.dataType as string,
        value: param.value as Parameter['value'],
      };
      if (param.parameterType === 'LIST' && param.members) {
        toPush.members = param.members as unknown[];
      } else if (param.parameterType === 'QUANTITATIVE_DATE') {
        toPush.minDate = param.minDate as string | null;
        toPush.maxDate = param.maxDate as string | null;
        toPush.periodValue = param.periodValue as number | null;
        toPush.periodType = param.periodType as string | null;
      } else if (param.parameterType === 'QUANTITATIVE_RANGE') {
        toPush.min = param.min as number | null;
        toPush.max = param.max as number | null;
        toPush.step = param.step as number | null;
      }
      combinedFields.parameters.push(toPush);
    }
  }

  // Enrich fields with GraphQL data
  const ds = listFieldsResult.data.publishedDatasources[0];
  if (ds?.fields.length) {
    for (const field of fields) {
      const match = ds.fields.find((f) => f.name === field.name);
      if (match) {
        populateFieldWithAdditionalProperties(match as unknown as Record<string, unknown>, field);
      }
    }
  }

  combinedFields.fieldGroups = groupFieldsByLogicalTableId(fields);
  return combinedFields;
}
