from __future__ import annotations

from typing import Any


def get_graphql_query(datasource_luid: str) -> str:
    return f"""
  query datasourceFieldInfo {{
    publishedDatasources(filter: {{ luid: "{datasource_luid}" }}) {{
      name
      description
      owner {{
        name
      }}
      fields {{
        name
        isHidden
        description
        descriptionInherited {{
          attribute
          value
        }}
        fullyQualifiedName
        __typename
        upstreamTables {{
          name
        }}
        ... on AnalyticsField {{
          __typename
        }}
        ... on ColumnField {{
          dataCategory
          role
          dataType
          defaultFormat
          semanticRole
          aggregation
          aggregationParam
        }}
        ... on CalculatedField {{
          dataCategory
          role
          dataType
          defaultFormat
          semanticRole
          aggregation
          aggregationParam
          formula
          isAutoGenerated
          hasUserReference
        }}
        ... on BinField {{
          dataCategory
          role
          dataType
          formula
          binSize
        }}
        ... on GroupField {{
          dataCategory
          role
          dataType
          hasOther
        }}
        ... on CombinedSetField {{
          delimiter
          combinationType
        }}
      }}
    }}
  }}"""


def _normalize_logical_table_id(logical_table_id: str | None) -> str | None:
    if logical_table_id is None:
        return None
    normalized = logical_table_id.strip()
    return normalized if normalized else None


def _group_fields_by_logical_table_id(
    fields: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    grouped: dict[str | None, list[dict[str, Any]]] = {}
    for field in fields:
        key = field.get("logicalTableId")
        grouped.setdefault(key, []).append(field)
    return [{"logicalTableId": k, "fields": v} for k, v in grouped.items()]


def _populate_field_with_additional_properties(source_field: dict[str, Any], target_field: dict[str, Any]) -> None:
    if source_field.get("description"):
        target_field["description"] = source_field["description"]
    desc_inherited = source_field.get("descriptionInherited")
    if isinstance(desc_inherited, list) and desc_inherited:
        target_field["descriptionInherited"] = desc_inherited
    if source_field.get("dataCategory"):
        target_field["dataCategory"] = source_field["dataCategory"]
    if source_field.get("role"):
        target_field["role"] = source_field["role"]
    if source_field.get("defaultFormat"):
        target_field["defaultFormat"] = source_field["defaultFormat"]
    if source_field.get("formula"):
        target_field["formula"] = source_field["formula"]
        if source_field.get("isAutoGenerated") is not None:
            target_field["isAutoGenerated"] = source_field["isAutoGenerated"]
        if source_field.get("hasUserReference") is not None:
            target_field["hasUserReference"] = source_field["hasUserReference"]
    if source_field.get("binSize") is not None:
        target_field["binSize"] = source_field["binSize"]


def _build_parameters(extra_data: dict[str, Any] | None) -> list[dict[str, Any]]:
    if not extra_data or not extra_data.get("parameters"):
        return []
    parameters: list[dict[str, Any]] = []
    for param in extra_data["parameters"]:
        entry: dict[str, Any] = {
            "name": param.get("parameterCaption"),
            "parameterType": param.get("parameterType"),
            "dataType": param.get("dataType"),
            "value": param.get("value"),
        }
        param_type = param.get("parameterType")
        if param_type == "LIST" and param.get("members"):
            entry["members"] = param["members"]
        elif param_type == "QUANTITATIVE_DATE":
            entry["minDate"] = param.get("minDate")
            entry["maxDate"] = param.get("maxDate")
            entry["periodValue"] = param.get("periodValue")
            entry["periodType"] = param.get("periodType")
        elif param_type == "QUANTITATIVE_RANGE":
            entry["min"] = param.get("min")
            entry["max"] = param.get("max")
            entry["step"] = param.get("step")
        parameters.append(entry)
    return parameters


def simplify_read_metadata_result(
    read_metadata_result: dict[str, Any],
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "datasourceDescription": "",
        "fieldGroups": [],
        "parameters": [],
    }

    data = read_metadata_result.get("data")
    if not data:
        return result

    fields: list[dict[str, Any]] = []
    for field in data:
        entry: dict[str, Any] = {
            "name": field.get("fieldCaption"),
            "dataType": field.get("dataType"),
            "columnClass": field.get("columnClass"),
            "logicalTableId": _normalize_logical_table_id(field.get("logicalTableId")),
        }
        if field.get("defaultAggregation"):
            entry["defaultAggregation"] = field["defaultAggregation"]
        if field.get("formula"):
            entry["formula"] = field["formula"]
        fields.append(entry)

    result["parameters"] = _build_parameters(read_metadata_result.get("extraData"))
    result["fieldGroups"] = _group_fields_by_logical_table_id(fields)
    return result


def combine_fields(
    read_metadata_result: dict[str, Any],
    list_fields_result: dict[str, Any],
) -> dict[str, Any]:
    ds_list = list_fields_result.get("data", {}).get("publishedDatasources", [])
    ds = ds_list[0] if ds_list else None

    combined: dict[str, Any] = {
        "datasourceDescription": (ds.get("description") or "") if ds else "",
        "fieldGroups": [],
        "parameters": [],
    }

    data = read_metadata_result.get("data")
    fields: list[dict[str, Any]] = []

    if not data:
        # Fallback to GraphQL results
        if ds and ds.get("fields"):
            for field in ds["fields"]:
                entry: dict[str, Any] = {
                    "name": field.get("name"),
                    "logicalTableId": None,
                }
                if field.get("dataType"):
                    entry["dataType"] = field["dataType"]
                if field.get("aggregation"):
                    entry["defaultAggregation"] = field["aggregation"]
                _populate_field_with_additional_properties(field, entry)
                fields.append(entry)
        combined["fieldGroups"] = _group_fields_by_logical_table_id(fields)
        return combined

    # Build fields from VizQL Data Service
    for field in data:
        entry = {
            "name": field.get("fieldCaption"),
            "dataType": field.get("dataType"),
            "columnClass": field.get("columnClass"),
            "logicalTableId": _normalize_logical_table_id(field.get("logicalTableId")),
        }
        if field.get("defaultAggregation"):
            entry["defaultAggregation"] = field["defaultAggregation"]
        if field.get("formula"):
            entry["formula"] = field["formula"]
        fields.append(entry)

    combined["parameters"] = _build_parameters(read_metadata_result.get("extraData"))

    # Enrich fields with GraphQL data
    if ds and ds.get("fields"):
        for field in fields:
            match = next((f for f in ds["fields"] if f.get("name") == field.get("name")), None)
            if match:
                _populate_field_with_additional_properties(match, field)

    combined["fieldGroups"] = _group_fields_by_logical_table_id(fields)
    return combined
